# Generated by Django 4.2.13 on 2026-05-29 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste')], max_length=10, verbose_name='Tipo')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('stock_anterior', models.IntegerField(verbose_name='Stock anterior')),
                ('stock_posterior', models.IntegerField(verbose_name='Stock posterior')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio unitario')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha'],
            },
        ),
    ]
